permalink: /:categories/:title/
baseurl: http://yankuang608.github.io
githubpage: https://github.com/yankuang608
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
imgurl: http://qc8conjyt.bkt.clouddn.com